export const START_FETCH_BASIN_MAP_URL = 'START_FETCH_BASIN_MAP_URL';
export const SUCCESS_FETCH_BASIN_MAP_URL = 'SUCCESS_FETCH_BASIN_MAP_URL';
export const ERROR_FETCH_BASIN_MAP_URL = 'ERROR_FETCH_BASIN_MAP_URL';

export const START_FETCH_CRF_URL = 'START_FETCH_CRF_URL';
export const SUCCESS_FETCH_CRF_URL = 'SUCCESS_FETCH_CRF_URL';
export const ERROR_FETCH_CRF_URL = 'ERROR_FETCH_CRF_URL';

export const START_GET_USER_SETTING = 'START_GET_USER_SETTING';
export const SUCCESS_GET_USER_SETTING = 'SUCCESS_GET_USER_SETTING';
export const ERROR_GET_USER_SETTING = 'ERROR_GET_USER_SETTING';

export const START_CREATE_USER_SETTING = 'START_CREATE_USER_SETTING';
export const SUCCESS_CREATE_USER_SETTING = 'SUCCESS_CREATE_USER_SETTING';
export const ERROR_CREATE_USER_SETTING = 'ERROR_CREATE_USER_SETTING';

export const START_UPDATE_USER_SETTING = 'START_UPDATE_USER_SETTING';
export const SUCCESS_UPDATE_USER_SETTING = 'SUCCESS_UPDATE_USER_SETTING';
export const ERROR_UPDATE_USER_SETTING = 'ERROR_UPDATE_USER_SETTING';

export const START_CREATE_TRASH_LOGGER = 'START_CREATE_TRASH_LOGGER';
export const SUCCESS_CREATE_TRASH_LOGGER = 'SUCCESS_CREATE_TRASH_LOGGER';
export const ERROR_CREATE_TRASH_LOGGER = 'ERROR_CREATE_TRASH_LOGGER';

export const START_CREATE_POLLUTION_REPORT = 'START_CREATE_POLLUTION_REPORT';
export const SUCCESS_CREATE_POLLUTION_REPORT = 'SUCCESS_CREATE_POLLUTION_REPORT';
export const ERROR_CREATE_POLLUTION_REPORT = 'ERROR_CREATE_POLLUTION_REPORT';

export const GET_AUTHORITY_CONTACT = 'GET_AUTHORITY_CONTACT';
export const GET_LAKE_LEVELS = 'GET_LAKE_LEVELS';

export const START_GET_DAM_DETAILS = 'START_GET_DAM_DETAILS';
export const SUCCESS_GET_DAM_DETAILS = 'SUCCESS_GET_DAM_DETAILS';

export const START_GET_FLOW_ARRIVAL_LOCATION = 'START_GET_FLOW_ARRIVAL_LOCATION';
export const SUCCESS_GET_FLOW_ARRIVAL_LOCATION = 'SUCCESS_GET_FLOW_ARRIVAL_LOCATION';

export const START_FETCH_FOLLOW_US_PAGE_URL = 'START_FETCH_FOLLOW_US_PAGE_URL';
export const SUCCESS_FETCH_FOLLOW_US_PAGE_URL = 'SUCCESS_FETCH_FOLLOW_US_PAGE_URL';
export const ERROR_FETCH_FOLLOW_US_PAGE_URL = 'ERROR_FETCH_FOLLOW_US_PAGE_URL';
