export const START_FETCH_BASIN_MAP_URL = 'START_FETCH_BASIN_MAP_URL';
export const SUCCESS_FETCH_BASIN_MAP_URL = 'SUCCESS_FETCH_BASIN_MAP_URL';
export const ERROR_FETCH_BASIN_MAP_URL = 'ERROR_FETCH_BASIN_MAP_URL';

export const START_FETCH_CRF_URL = 'START_FETCH_CRF_URL';
export const SUCCESS_FETCH_CRF_URL = 'SUCCESS_FETCH_CRF_URL';
export const ERROR_FETCH_CRF_URL = 'ERROR_FETCH_CRF_URL';
