export const START_FETCH_BASIN_MAP_URL = 'START_FETCH_BASIN_MAP_URL';
export const SUCCESS_FETCH_BASIN_MAP_URL = 'SUCCESS_FETCH_BASIN_MAP_URL';
export const ERROR_FETCH_BASIN_MAP_URL = 'ERROR_FETCH_BASIN_MAP_URL';

export const START_FETCH_CRF_URL = 'START_FETCH_CRF_URL';
export const SUCCESS_FETCH_CRF_URL = 'SUCCESS_FETCH_CRF_URL';
export const ERROR_FETCH_CRF_URL = 'ERROR_FETCH_CRF_URL';

export const START_GET_USER_SETTING = 'START_GET_USER_SETTING';
export const SUCCESS_GET_USER_SETTING = 'SUCCESS_GET_USER_SETTING';
export const ERROR_GET_USER_SETTING = 'ERROR_GET_USER_SETTING';

export const START_CREATE_USER_SETTING = 'START_CREATE_USER_SETTING';
export const SUCCESS_CREATE_USER_SETTING = 'SUCCESS_CREATE_USER_SETTING';
export const ERROR_CREATE_USER_SETTING = 'ERROR_CREATE_USER_SETTING';

export const START_UPDATE_USER_SETTING = 'START_UPDATE_USER_SETTING';
export const SUCCESS_UPDATE_USER_SETTING = 'SUCCESS_UPDATE_USER_SETTING';
export const ERROR_UPDATE_USER_SETTING = 'ERROR_UPDATE_USER_SETTING';
